# /etc/fail2ban/filter.d/asterisk-scan.conf
# Detecta varredura de extensões/ramais (enumeration attack)

[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk

# Padrões: tentativas em ramais que não existem
failregex = ^.*Request '\S+' from .* failed for '<HOST>:\d+'.*No matching endpoint found.*$
            ^.*SecurityEvent="InvalidAccountID".*RemoteAddress=.*\b<HOST>\b.*$
            ^.*No such file or directory.*<HOST>.*$

ignoreregex =
