# /etc/fail2ban/filter.d/asterisk-flood.conf
# Detecta flood de pacotes SIP (OPTIONS flood, REGISTER flood)

[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk

failregex = ^.*from.*<HOST>.*OPTIONS.*$
            ^.*Retransmitting #.*to.*<HOST>.*$

ignoreregex = ^.*127\.0\.0\.1.*$
              ^.*10\.\d+\.\d+\.\d+.*$
              ^.*192\.168\.\d+\.\d+.*$
